# Generated by Django 5.2.7 on 2025-11-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_remove_order_cart_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do evento')),
                ('local', models.CharField(max_length=150, verbose_name='Local do evento')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade do evento')),
                ('data', models.DateField(verbose_name='Data do evento')),
                ('descricao', models.TextField(verbose_name='Descrição detalhada')),
                ('imagem', models.URLField(max_length=300, verbose_name='Imagem de capa')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço base do ingresso')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
