# Generated by Django 5.2.7 on 2025-11-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.AlterField(
            model_name='evento',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
