# Generated by Django 5.2.7 on 2025-11-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_evento_options_alter_evento_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.URLField(max_length=300),
        ),
    ]
