# Generated by Django 5.2.7 on 2025-11-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_evento_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='preco',
            new_name='ingresso',
        ),
        migrations.AddField(
            model_name='evento',
            name='excursao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
