# Generated by Django 5.2.7 on 2025-11-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='preco_unitario',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='preco_excursao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='preco_ingresso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
